{
  "Author": "This document was written by Jeff Gennari.",
  "CAM_AttackerAccessRequired": "0",
  "CAM_EaseOfExploitation": "0",
  "CAM_Exploitation": "0",
  "CAM_Impact": "0",
  "CAM_InternetInfrastructure": "0",
  "CAM_Population": "0",
  "CAM_ScoreCurrent": 0,
  "CAM_ScoreCurrentWidelyKnown": 0,
  "CAM_ScoreCurrentWidelyKnownExploited": 0,
  "CAM_WidelyKnown": "0",
  "CERTAdvisory": "",
  "CVEIDs": "CVE-2006-4980",
  "CVSS_AccessComplexity": "--",
  "CVSS_AccessVector": "--",
  "CVSS_Authenication": "--",
  "CVSS_AvailabilityImpact": "--",
  "CVSS_BaseScore": 0,
  "CVSS_BaseVector": "AV:--/AC:--/Au:--/C:--/I:--/A:--",
  "CVSS_CollateralDamagePotential": "Not Defined (ND)",
  "CVSS_ConfidentialityImpact": "--",
  "CVSS_EnvironmentalScore": 0,
  "CVSS_EnvironmentalVector": "CDP:Not Defined (ND)/TD:Not Defined (ND)/CR:Not Defined (ND)/IR:Not Defined (ND)/AR:Not Defined (ND)",
  "CVSS_Exploitability": "Not Defined (ND)",
  "CVSS_IntegrityImpact": "--",
  "CVSS_RemediationLevel": "Not Defined (ND)",
  "CVSS_ReportConfidence": "Not Defined (ND)",
  "CVSS_SecurityRequirementsAR": "Not Defined (ND)",
  "CVSS_SecurityRequirementsCR": "Not Defined (ND)",
  "CVSS_SecurityRequirementsIR": "Not Defined (ND)",
  "CVSS_TargetDistribution": "Not Defined (ND)",
  "CVSS_TemporalScore": 0,
  "CVSS_TemporalVector": "E:Not Defined (ND)/RL:Not Defined (ND)/RC:Not Defined (ND)",
  "DateCreated": "2006-10-26T12:40:19-04:00",
  "DateFirstPublished": "",
  "DateLastUpdated": "2007-01-11T08:44:00-05:00",
  "DatePublic": "2006-10-06T00:00:00",
  "Description": "",
  "ID": "VU#169512",
  "IDNumber": "169512",
  "IPProtocol": "",
  "Impact": "The complete impact of this vulnerability is not yet known.",
  "Keywords": [
    "Python",
    "DoS",
    "arbitrary code execution",
    "repr",
    "UTF-32",
    "UCS-4"
  ],
  "Overview": "",
  "References": [
    "http://sourceforge.net/tracker/index.php?func=detail&aid=1541585&group_id=5470&atid=305470 ",
    "http://zoehep.xent.com/~bsittler/python2.4-2.4.3_unicodeobject.c.diff ",
    "https://launchpad.net/distros/ubuntu/+source/python2.4/+bug/56633 ",
    "http://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=208162 ",
    "https://issues.rpath.com/browse/RPL-702 ",
    "http://support.avaya.com/elmodocs2/security/ASA-2006-229.htm ",
    "http://www.securityfocus.com/bid/20376 ",
    "http://www.frsirt.com/english/advisories/2006/3940 ",
    "http://securitytracker.com/id?1017019 ",
    "http://secunia.com/advisories/22276 ",
    "http://secunia.com/advisories/22303 ",
    "http://secunia.com/advisories/22357 ",
    "http://secunia.com/advisories/22297 ",
    "http://secunia.com/advisories/22358 ",
    "http://secunia.com/advisories/22379 ",
    "http://secunia.com/advisories/22448 ",
    "http://secunia.com/advisories/22512 ",
    "http://secunia.com/advisories/22639/",
    "http://xforce.iss.net/xforce/xfdb/29408 ",
    "http://secunia.com/advisories/23680/"
  ],
  "Resolution": "The CERT/CC is currently unaware of a practical solution to this problem.",
  "Revision": 8,
  "SystemsAffectedPreamble": "",
  "ThanksAndCredit": "",
  "Title": "Python \"repr\" function fails to handle crafted wide character UTF-32/UCS-4 strings",
  "US-CERTTechnicalAlert": "",
  "VRDA_D1_DirectReport": "0",
  "VRDA_D1_Impact": "3",
  "VRDA_D1_Population": "3",
  "VulnerabilityCount": 1,
  "Workarounds": ""
}